export const data = [
  {
    model: "Honda Civic",
    name: "Honda",
    email: "xavier.basurto.77@gmail.com",
    phone: "1234567890",
    department: "Lima",
    city: "Lima",
  },
  {
    model: "Toyota Corolla",
    name: "Toyota",
    email: "daniel.martinez.88@gmail.com",
    phone: "1234567890",
    department: "Lima",
    city: "Lima",
  },
  {
    model: "Ford Mustang",
    name: "Ford",
    email: "jose.garcia.99@gmail.com",
    phone: "1234567890",
    department: "Lima",
    city: "Lima",
  },
  {
    model: "sport",
    name: "sport",
    email: "jose.garcia.99@gmail.com",
    phone: "1234567890",
    department: "Lima",
    city: "Lima",
  },
  {
    model: "sedan",
    name: "sedan",
    email: "jose.garcia.99@gmail.com",
    phone: "1234567890",
    department: "Lima",
    city: "Lima",
  },
  {
    model: "suv",
    name: "suv",
    email: "jose.garcia.99@gmail.com",
    phone: "1234567890",
    department: "Lima",
    city: "Lima",
  },
];
